version: '3'
services:
    db:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: semdb

    app:
        build:
          context: .
          dockerfile: Dockerfile
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/semdb
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: 1234
            SPRING_JPA_HIBERNATE_DDL_AUTO: validate
            STORAGE_LOCATION: /opt/app/img
        ports:
            - '8080:8080'
        depends_on:
            - db
